version: '2.3'

services:
  josezambudiobernabeu:
    container_name: josezambudiobernabeu
    build:
      context: ./web
      dockerfile: Dockerfile-prod
    networks:
      - proxy-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:josezambudiobernabeu.com'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.docker.network=proxy-network'

networks:
  proxy-network:
    external: true
