version: '2.3'

services:
  web:
    network_mode: host
    build:
      context: ./
    environment:
      NODE_UID: ${NODE_UID:-501}
      NODE_GID: ${NODE_GID:-20}
      NODE_ENV: ${NODE_ENV:-development}
      DOMAIN: ${DOMAIN}
      SESSION_SECRET: ${SESSION_SECRET}
    volumes:
      - './portfolio:${PROJECT_PWD}/portfolio'
    working_dir: ${PROJECT_PWD}/portfolio
    ports:
      - '3000:3000'
      - '10000:10000'
      - '10001:10001'
#     depends_on:
#       - redis

#   redis:
#     image: redis:4.0-alpine
#     volumes:
#       - redis-volume:/data

# volumes:
#   redis-volume:
#     driver_opts:
#       type: tmpfs
#       device: tmpfs
