version: '2.3'

services:
  josezambudiobernabeu:
    container_name: josezambudiobernabeu
    build:
      context: ./web
      args:
        NODE_UID: ${USER_UID:-501}
        NODE_GID: ${USER_GID:-20}
        NODE_ENV: development
    volumes:
      - './web:${PROJECT_PWD}/web'
    ports:
      - '9000:9000'
      - '9005:9005'
    working_dir: ${PROJECT_PWD}/web
