version: '2.3'

services:
  cv_node:
    container_name: cv_node
    build:
      context: ./web
      args:
        NODE_UID: ${USER_UID:-501}
        NODE_GID: ${USER_GID:-20}
        NODE_ENV: development
    volumes:
      - './web:${PROJECT_PWD}/web'
    working_dir: ${PROJECT_PWD}/web
